export const nichesCategories: string[] = [
  "Weightlifting",
  "Yoga",
  "Jogging",
  "Meditation",
  "Fitness sports",
  "E-sports",
  "Hiking",
  "Mental health",
  "Psychology",
  "Alternative medicines",
  "Natural medicines",
  "Messages",
  "Skincare",
  "Lose weight",
  "Muscle growth",
  "Exercise at home",
  "Cars",
  "Engines",
  "Gaming",
  "Technology",
  "Gadgets",
  "Music",
  "Gardening",
  "Photography",
  "VideoGraphy",
  "Fishing",
  "Survivors",
  "Painting and art",
  "Movies",
  "Poker and gambling",
  "Writing",
  "Drones",
  "Books",
  "Cameras",
  "Virtual reality",
  "Computers",
];
